[package]
name = "starkcipher"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.9.2"

[[target.starknet-contract]]
sierra = true
casm = true

[profile.release]
overflow-checks = false
lto = true
codegen-units = 1

